apply plugin: 'com.android.application'
//apply plugin: 'com.android.library'

android {
    compileSdkVersion 34
    namespace 'com.styluslabs.writeqt'
    defaultConfig {
        applicationId "com.styluslabs.writeqt"
        versionCode 24
        versionName "3.0.24"
        // SDK 18 for GLES 3.0 (linking fails for ES3.1 fns for armv7), SDK 21 for GLES 3.1
        minSdkVersion 23
        targetSdkVersion 34
        externalNativeBuild {
            ndkBuild {
                arguments "APP_PLATFORM=android-22", "V=1", "WRITE_HOME=/Users/ozpineci/android_dev/write_apps/Write_github"
                abiFilters 'arm64-v8a'
            }
        }
    }

    buildTypes {
        release {
            // remove this to produced unsigned APK for upload to Google Play (after manually signing)
            signingConfig signingConfigs.debug
            // enable this for Google Play APK
            minifyEnabled false
            // to add release specific compiler flags, add cFlags or cppFlags here
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            ndk {
                abiFilters 'arm64-v8a'
            }
        }
        arm64rel {
            //initWith(buildTypes.release)
            signingConfig signingConfigs.debug
            minifyEnabled false
            ndk {
                abiFilters 'arm64-v8a'
            }
        }
        x86rel {
            signingConfig signingConfigs.debug
            minifyEnabled false
            ndk {
                abiFilters 'x86'
            }
        }
    }

    sourceSets.main {
        jniLibs.srcDir 'libs'
    }
    externalNativeBuild {
        ndkBuild {
            path 'src/main/jni/Android.mk'
        }
    }
    ndkVersion '26.3.11579264'


    lintOptions {
        // google suddenly decided I needed to download intellij, kotlin, groovy, play-sdk, etc. to build a simple APK
        checkReleaseBuilds false
        abortOnError false
        disable 'ExpiredTargetSdkVersion'
    }
packagingOptions {
    pickFirst 'lib/arm64-v8a/libc++_shared.so'
    pickFirst 'lib/armeabi-v7a/libc++_shared.so'
    pickFirst 'lib/x86/libc++_shared.so'
    pickFirst 'lib/x86_64/libc++_shared.so'
jniLibs {
        useLegacyPackaging = true
    }
}

}
configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}

repositories {
    maven { url "https://jitpack.io" }
    maven {
        url "http://repo.boox.com/repository/maven-public/"
        allowInsecureProtocol true
    }
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'androidx.core:core:1.12.0'
    //implementation 'com.android.support:support-v4:28.0.0'  
    implementation 'com.onyx.android.sdk:onyxsdk-pen:1.4.11'
    implementation 'com.onyx.android.sdk:onyxsdk-device:1.2.30'
    implementation 'org.lsposed.hiddenapibypass:hiddenapibypass:4.3'
}
