name: Write CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linux-build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      run: git clone --recurse-submodules https://github.com/styluslabs/Write
    #- run: git clone --recurse-submodules https://github.com/styluslabs/Write
    # can't switch branch of submodule from actions/checkout: https://github.com/actions/checkout/issues/1815
    #- run: git switch write-linux
    #  working-directory: Write/SDL
    #- uses: actions/checkout@v4
    #  with:
    #    submodules: recursive
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libsdl2-dev
    - name: Build SDL
      working-directory: SDL
      run: |
        git switch write-linux
        make -f ../scribbleres/SDL-Makefile.unix DEBUG=0
        make -f ../scribbleres/SDL-Makefile.unix DEBUG=1
        ln -s ../include Release/include
    # test doesn't work because SDL init fails due to no video device
    #- run: make DEBUG=1 SANITIZE=0 USE_SYSTEM_SDL=0
    #  working-directory: syncscribble
    #- run: ./Debug/Write --glRender=0 --test
    #  working-directory: syncscribble
    - run: make DEBUG=0 USE_SYSTEM_SDL=0 real_tgz
      working-directory: syncscribble
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
    - name: Upload release tgz
      uses: actions/upload-artifact@v4
      with:
        name: release-22_04-tgz
        path: syncscribble/Release/*.tar.gz

  windows-build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      run: git clone --recurse-submodules https://github.com/styluslabs/Write
    - name: Download make.exe
      run: curl -L -o make.exe https://github.com/styluslabs/maps/releases/download/alpha-1/make.exe
    - name: MSVC command prompt
      uses: ilammy/msvc-dev-cmd@v1
    - name: Build SDL
      shell: cmd
      working-directory: Write/SDL
      run: |
        git switch write-win
        ..\..\make.exe -f ..\scribbleres\SDL-Makefile.msvc SHELL=cmd.exe
    - name: Build Write
      shell: cmd
      working-directory: Write/syncscribble
      run: ..\..\make.exe SHELL=cmd.exe DEBUG=0 zip
    # SSH session to debug workflow
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
    - name: Upload release ZIP
      uses: actions/upload-artifact@v4
      with:
        name: release-win64-zip
        path: Write/syncscribble/Release/*.zip

  android-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      run: git clone --recurse-submodules https://github.com/styluslabs/Write
    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Gradle Assemble
      run: ./gww assembleRelease
      working-directory: Write/syncscribble/android
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: ${{ failure() }}
    - name: Upload release APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release-apk
        path: Write/syncscribble/android/app/build/outputs/apk/release/app-release.apk
